In [1]:
import numpy as np

## Making Matrices of Dezired Shape

#### Zero Vector

In [2]:
x = np.zeros((3,1))
print('Vector :\n',x,'\n')
print('Shape :',x.shape)

Vector :
 [[0.]
 [0.]
 [0.]] 

Shape : (3, 1)


#### Zero Matrices 

In [3]:
x = np.zeros((3,4))
print('Matrix :\n',x,'\n')
print('Shape :',x.shape)
print('Rows : ',x.shape[0])
print('Columns :',x.shape[1])

Matrix :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Shape : (3, 4)
Rows :  3
Columns : 4


#### Ones Vector

In [4]:
x = np.ones((3,1))
print('Vector :\n',x,'\n')
print('Shape :',x.shape)

Vector :
 [[1.]
 [1.]
 [1.]] 

Shape : (3, 1)


#### Ones Matrix 

In [5]:
x = np.ones((3,4))
print('Matrix :\n',x,'\n')
print('Shape :',x.shape)
print('Rows : ',x.shape[0])
print('Columns :',x.shape[1])

Matrix :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Shape : (3, 4)
Rows :  3
Columns : 4


#### Random Vectors and Matrices

In [6]:
x = np.random.rand(3,1)
print(x)

[[0.46930259]
 [0.29101471]
 [0.23713545]]


In [7]:
x = np.random.randn(3,1)
print(x)

[[-0.85079371]
 [ 0.92970735]
 [ 2.31028664]]


In [8]:
x = np.random.rand(3,4)
print(x)

[[0.16318187 0.02378397 0.60896135 0.62264527]
 [0.67852465 0.59899026 0.46167467 0.89510339]
 [0.38999779 0.52219421 0.2000156  0.71990018]]


In [9]:
x = np.random.randn(3,4)
print(x)

[[ 0.54434771 -0.78056448  0.05425946  0.67508937]
 [ 0.8202727  -0.46733587 -0.96980644  1.63251083]
 [-0.840114    0.41386172  0.27954149 -0.0299406 ]]


## NOTE:
#### np.random.randn generates samples from normal  distribution
#### np.random.rand   generates samples from uniform distribution

### Matrix Multiplication

In [10]:
A = np.array([[1,2,3],[3,4,5]])
print('A :\n',A)
print('Shape :',A.shape,'\n')

B = np.array([[1,2],[3,4],[5,6]])
print('B :\n',B)
print('Shape :',B.shape,'\n')

C = np.dot(A,B)
print('C :\n',C)
print('Shape :',C.shape)

A :
 [[1 2 3]
 [3 4 5]]
Shape : (2, 3) 

B :
 [[1 2]
 [3 4]
 [5 6]]
Shape : (3, 2) 

C :
 [[22 28]
 [40 52]]
Shape : (2, 2)


### Transpose of Matrix

In [11]:
A = np.array([[1,2],
              [3,4],
              [5,6]])
print('A :\n',A)
print('Shape :',A.shape)
print('\n')
A_transpose = A.T
print('Transpose A:\n',A_transpose)
print('Shape :',A_transpose.shape)

A :
 [[1 2]
 [3 4]
 [5 6]]
Shape : (3, 2)


Transpose A:
 [[1 3 5]
 [2 4 6]]
Shape : (2, 3)


### Why numpy is fast???

In [12]:
A = np.random.rand(5000000,1)
B = np.random.rand(5000000,1)

### Both A and B have 5 million entries; let us see how much time it takes when we get their dot product in a conventional way

In [13]:
import time

In [18]:
C = np.zeros((5000000,1))
tic = time.time()
for i in range(5000000):
    C[i][0] = A[i][0]*B[i][0]
toc = time.time()
print('Time Needed using for loop : ',(toc-tic)*100,'ms')
print(C.shape)

Time Needed using for loop :  1224.499225616455 ms
(5000000, 1)


#### Using inbuilt numpy functions

In [19]:
tic = time.time()
C = A*B
toc = time.time()
print('Time Needed without for loop : ',(toc-tic)*100,'ms')
print(C.shape)

Time Needed without for loop :  3.8010120391845703 ms
(5000000, 1)


### Thus we can see how fast numpy is!!!

#### Reshaping a Vector

In [23]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print('Shape :',x.shape)
print('\n')
a = x.reshape(3,2)
print(a)
print('Shape :',a.shape)

[[1 2 3]
 [4 5 6]]
Shape : (2, 3)


[[1 2]
 [3 4]
 [5 6]]
Shape : (3, 2)


### Python Broadcasting

In [35]:
x = np.array([[1,1,1],
             [1,1,1]])
print(x+1)

[[2 2 2]
 [2 2 2]]


In [36]:
v = [[1],
     [2]]
print(x+v)

[[2 2 2]
 [3 3 3]]


In [38]:
v1 = [[1,2,3]]
print(x+v1)

[[2 3 4]
 [2 3 4]]


In [25]:
x = np.array([[0,3,4],
             [2,6,4]])
print(x)

[[0 3 4]
 [2 6 4]]


##### Normalizing each row

In [29]:
x_norm = np.linalg.norm(x,axis=1,keepdims=True)
print(x_norm)

[[5.        ]
 [7.48331477]]


In [30]:
print(x/x_norm)

[[0.         0.6        0.8       ]
 [0.26726124 0.80178373 0.53452248]]


##### What if we normalize each column

In [31]:
x_norm_1 = np.linalg.norm(x,axis=0,keepdims=True)
print(x_norm_1)

[[2.         6.70820393 5.65685425]]


In [32]:
print(x/x_norm_1)

[[0.         0.4472136  0.70710678]
 [1.         0.89442719 0.70710678]]
